/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.workflow.kaleo.internal.util;

import com.liferay.account.constants.AccountConstants;
import com.liferay.account.model.AccountRole;
import com.liferay.account.service.AccountRoleLocalServiceUtil;
import com.liferay.batch.engine.thread.local.BatchEngineThreadLocal;
import com.liferay.exportimport.kernel.empty.model.EmptyModelManagerUtil;
import com.liferay.petra.function.transform.TransformUtil;
import com.liferay.petra.lang.SafeCloseable;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.exception.DuplicateRoleException;
import com.liferay.portal.kernel.exception.NoSuchRoleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.lazy.referencing.LazyReferencingThreadLocal;
import com.liferay.portal.kernel.model.Role;
import com.liferay.portal.kernel.model.role.RoleConstants;
import com.liferay.portal.kernel.service.RoleLocalServiceUtil;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.HashMapBuilder;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.roles.admin.role.type.contributor.RoleTypeContributor;
import com.liferay.roles.admin.role.type.contributor.provider.RoleTypeContributorProvider;

import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.osgi.util.tracker.ServiceTracker;

/**
 * @author Michael C. Han
 */
public class RoleUtil {

	public static Role getRole(
			String externalReferenceCode, long roleId,
			ServiceContext serviceContext)
		throws PortalException {

		Role role = null;

		if (Validator.isNotNull(externalReferenceCode)) {
			role = RoleLocalServiceUtil.fetchRoleByExternalReferenceCode(
				externalReferenceCode, serviceContext.getCompanyId());
		}

		if (role == null) {
			role = RoleLocalServiceUtil.fetchRole(roleId);
		}

		if (role != null) {
			return role;
		}

		if (Validator.isNull(externalReferenceCode) ||
			!BatchEngineThreadLocal.isBatchImportInProcess()) {

			return RoleLocalServiceUtil.getRole(roleId);
		}

		try (SafeCloseable safeCloseable =
				LazyReferencingThreadLocal.setEnabledWithSafeCloseable(true)) {

			return RoleLocalServiceUtil.getOrAddEmptyRole(
				externalReferenceCode, serviceContext.getCompanyId(),
				serviceContext.getUserId(), null, 0, externalReferenceCode,
				RoleConstants.TYPE_REGULAR);
		}
	}

	public static Role getRole(
			String externalReferenceCode, String name, int roleType,
			boolean autoCreate, ServiceContext serviceContext)
		throws PortalException {

		Role role = _getOrAddRole(
			externalReferenceCode, name, roleType, autoCreate, serviceContext);

		if (role.getType() != roleType) {
			throw new DuplicateRoleException(
				"Role already exists with name " + name);
		}

		return role;
	}

	public static List<Long> getRoleIds(ServiceContext serviceContext) {
		return TransformUtil.transform(
			RoleLocalServiceUtil.getUserRoles(serviceContext.getUserId()),
			role -> role.getRoleId());
	}

	public static int getRoleType(String roleType) {
		RoleTypeContributorProvider roleTypeContributorProvider =
			_serviceTracker.getService();

		for (RoleTypeContributor roleTypeContributor :
				roleTypeContributorProvider.getRoleTypeContributors()) {

			if (roleType.equals(roleTypeContributor.getTypeLabel())) {
				return roleTypeContributor.getType();
			}
		}

		if (roleType.equals(_LEGACY_TYPE_COMMUNITY_LABEL)) {
			return RoleConstants.TYPE_SITE;
		}

		return RoleConstants.getLabelType(roleType);
	}

	private static Role _getOrAddRole(
			String externalReferenceCode, String name, int roleType,
			boolean autoCreate, ServiceContext serviceContext)
		throws PortalException {

		long companyId = serviceContext.getCompanyId();

		Role role = null;

		if (Validator.isNotNull(externalReferenceCode)) {
			role = RoleLocalServiceUtil.fetchRoleByExternalReferenceCode(
				externalReferenceCode, companyId);
		}

		if (role == null) {
			role = RoleLocalServiceUtil.fetchRole(companyId, name);
		}

		if (role != null) {
			return role;
		}

		if (Validator.isNull(externalReferenceCode)) {
			externalReferenceCode =
				RoleConstants.toSystemRoleExternalReferenceCode(name);
		}

		if (!autoCreate) {
			EmptyModelManagerUtil.reportMissingReference(
				Role.class.getName(), externalReferenceCode,
				serviceContext.getScopeGroupId());

			throw new NoSuchRoleException(
				StringBundler.concat(
					"No Role exists with the key {companyId=",
					serviceContext.getCompanyId(), ", name=", name, "}"));
		}

		Map<Locale, String> descriptionMap = HashMapBuilder.put(
			LocaleUtil.getDefault(),
			"This is an autogenerated role from the workflow definition."
		).build();

		if (roleType == RoleConstants.TYPE_ACCOUNT) {
			AccountRole accountRole =
				AccountRoleLocalServiceUtil.addAccountRole(
					externalReferenceCode, serviceContext.getUserId(),
					AccountConstants.ACCOUNT_ENTRY_ID_DEFAULT, name, null,
					descriptionMap);

			return accountRole.getRole();
		}

		if (!BatchEngineThreadLocal.isBatchImportInProcess()) {
			return RoleLocalServiceUtil.addRole(
				externalReferenceCode, serviceContext.getUserId(), null, 0,
				name, null, descriptionMap, roleType, null, null);
		}

		try (SafeCloseable safeCloseable =
				LazyReferencingThreadLocal.setEnabledWithSafeCloseable(true)) {

			return RoleLocalServiceUtil.getOrAddEmptyRole(
				externalReferenceCode, serviceContext.getCompanyId(),
				serviceContext.getUserId(), null, 0, name, roleType);
		}
	}

	private static final String _LEGACY_TYPE_COMMUNITY_LABEL = "community";

	private static final ServiceTracker
		<RoleTypeContributorProvider, RoleTypeContributorProvider>
			_serviceTracker;

	static {
		Bundle bundle = FrameworkUtil.getBundle(
			RoleTypeContributorProvider.class);

		ServiceTracker<RoleTypeContributorProvider, RoleTypeContributorProvider>
			serviceTracker = new ServiceTracker<>(
				bundle.getBundleContext(), RoleTypeContributorProvider.class,
				null);

		serviceTracker.open();

		_serviceTracker = serviceTracker;
	}

}